language: elixir
matrix:
  include:
    - otp_release: 20.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.8
    - otp_release: 22.0
      elixir: 1.8
    - otp_release: 20.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 21.0
      elixir: 1.10
    - otp_release: 22.0
      elixir: 1.10
sudo: false
after_script:
  - MIX_ENV=docs mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis
  - mix dialyzer
cache:
  directories:
    - priv/plts
